<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
{
    DB::table('products')->insert([
        [
            'name' => 'Product 1',
            'quantity' => 100,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 49.99,
            'order_number' => 1,
            'label_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 2',
            'quantity' => 200,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 79.99,
            'order_number' => 2,
            'label_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 3',
            'quantity' => 300,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 99.99,
            'order_number' => 3,
            'label_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 4',
            'quantity' => 150,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 69.99,
            'order_number' => 4,
            'label_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 5',
            'quantity' => 250,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 89.99,
            'order_number' => 5,
            'label_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 6',
            'quantity' => 180,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 99.99,
            'order_number' => 6,
            'label_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 7',
            'quantity' => 120,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 59.99,
            'order_number' => 7,
            'label_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 8',
            'quantity' => 220,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 79.99,
            'order_number' => 8,
            'label_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 9',
            'quantity' => 280,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 99.99,
            'order_number' => 9,
            'label_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 10',
            'quantity' => 130,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 69.99,
            'order_number' => 10,
            'label_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 11',
            'quantity' => 210,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 99.99,
            'order_number' => 11,
            'label_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 12',
            'quantity' => 320,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 99.99,
            'order_number' => 12,
            'label_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 13',
            'quantity' => 140,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 79.99,
            'order_number' => 13,
            'label_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 14',
            'quantity' => 230,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 89.99,
            'order_number' => 14,
            'label_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Product 15',
            'quantity' => 280,
            'image' => 'https://dummyimage.com/540x650/0d22de/fff,https://dummyimage.com/540x650/53e821/fff',
            'images' => 'https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop,https://dummyimage.com/sqrpop',
            'price' => 99.99,
            'order_number' => 15,
            'label_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ],
    ]);
}


}
